---
functional:
  - Решение задачи на скорость против другого игрока
  - Оба игрока видят друг у друга редактор с кодом, вывод тестов
  - Игроки могут менять язык программирования во время решения
  - В игру можно играть с любым человеком, с ботом или другом
  - Игра доступна по ссылке
  - Можно выбрать игру по уровню сложности
  - При создании игры можно выбрать определенную задачу, иначе она будет подобрана наугад
  - Задачи даны на двух языках — русском и английском
  - Другие пользователи могут следить за ходом игры
  - В игре есть чат, в котором общаются зарегистрированные пользователи
  - Завершенная игра доступна в записи
  - Редактор для ввода кода выглядит как проигрыватель
  - Пользователи получают очки, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Игра должна поддерживать одновременное участие нескольких игроков без задержек
  - Чат должен работать в реальном времени
  - Система должна корректно отображать код и тесты для разных языков программирования
  - Рейтинговая система должна обновляться без задержек
  - Записи завершенных игр должны храниться без потерь данных
implicit:
  - Игра должна быть доступна 24/7
  - Данные пользователей (логины, пароли, чат) должны быть защищены
  - Интерфейс должен быть интуитивно понятным
  - Поддержка популярных браузеров и устройств
  - Минимальное время загрузки игры (оптимизация).
